### ISSUE TITLE
Windows (Command prompt) arrow keys not working

### ISSUE THREAD

**Issue by santiyounger** [liamvdv/doomsdaytutor#1]
Hey Thanks for the awesome tool! I managed to install it correctly, however upon trying to select a date, I can't move the cursor to choose the right day.

I tried to use all arrow keys, tab, and every key possible, but it's stuck
![image](https://user-images.githubusercontent.com/51902730/154714730-b4c51e50-0815-427f-bcb0-d6a170ff652b.png)
I'm unable to move down, so the only option I can click on is Sunday

Seems to be a problem with Windows

I'm on Windows 11 using Command Prompt, I'm downloading alternative terminal emulators to see if it solves it

Thanks a lot, can't wait to use this to practice

Let me know if there's any more info I can provide to help solve this!

**Comment by santiyounger** [comment]
Update:

unfortunately I tried different terminal emulators and I keep having the same problem with all of them

Hope it's solvable, really looking forward to use this awesome tool!

**Comment by liamvdv** [comment]
Hi santiyounger, 
thanks a lot for reaching out! You're officially the first person to open an issue in one of my projects - and it made my day :D.

Your issue is a known issue of inquirer, the library which handles the input. I'll need to look for equally suitable alternatives out there and reach out when I found one.

In the meantime, I'd love to know how you found this project in the depths of the internet.

Reference to [inquirer](https://github.com/CITGuru/PyInquirer) issue:
[https://github.com/CITGuru/PyInquirer/issues/159](https://github.com/CITGuru/PyInquirer/issues/159)  - tl;dr maintainer no longer active, looking for successor, Windows fix pending

**Comment by liamvdv** [comment]
Current solution is to switch to a InquirerPy.
I still need to do some testing on Linux to see if everthing works as expected, but Windows cmd and power shell should work. Expect version 0.2.0 to be released tomorrow (Sa 19.02.). 
Do you have any feedback on the colors used in the terminal? I noticed the initial dark blue message is quite hard to read on power shells blue background.

**Comment by santiyounger** [comment]
Hey Liam,
Thank you so much for your quick reply. So happy to hear I'm the first to write an issue, however this project deserves a lot more attention for sure!

I've been spending a couple hours using your awesome software. It's hands down the best out there. I love how you show the process of the doomsday calendar calculation.

Since I can't select the correct option _(due to navigation of keys not working)_ I'm forced to make a wrong guess everytime (Sunday) hahaha but even then, it's helpful to see the process to make sure I'm doing the right calculations.

This is a hobby I just got into, and I was looking for tools to practice, and I love this project
I found your project searching for _"github projects for learning "doomsday algorithm""_

**Comment by santiyounger** [comment]
> Do you have any feedback on the colors used in the terminal? I noticed the initial dark blue message is quite hard to read on power shells blue background.

I know what you mean, I try not to use the ugly powershell blue, I'm using some emulators to change colors. but I get you, I  wouldn't worry to much, I'm sure people that use powershell can change it to see it better, perhaps a slightly brighter blue could work for the text. 

but like I said powerusers will have their workaround

I'm using a nice windows emulator called tabby terminal, so I can pick colors and make it look like I like it, so again I wouldn't worry too much

**Comment by santiyounger** [comment]
>  Expect version 0.2.0 to be released tomorrow (Sa 19.02.).
Wow man you are awesome, thank you so much! definitely keep me updated and I'll test it out!

Have a great day man! keep up the incredible work!

**Comment by liamvdv** [comment]
Hi santiyounger,
doomsdaytutor v0.2.0 is available🚀. Install with `pip install doomsdaytutor`.
Enjoy!

**Comment by santiyounger** [comment]
Perfect Liam! thank you so much for solving it so soon! it worked and I'm so happy being able to fully use it!

This is my favorite terminal  utility, incredible work man, keep it up!
